-- Custom Orders Table for Custom Jewelry Requests
CREATE TABLE IF NOT EXISTS public.custom_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  
  -- Customer Information
  customer_first_name VARCHAR(255) NOT NULL,
  customer_last_name VARCHAR(255) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(20),
  
  -- Order Details
  order_title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  materials VARCHAR(255),
  budget_min DECIMAL(10,2),
  budget_max DECIMAL(10,2),
  timeline_weeks INTEGER,
  reference_images TEXT[], -- Array of image URLs
  special_requests TEXT,
  
  -- Status and Management
  status VARCHAR(50) DEFAULT 'submitted' CHECK (status IN (
    'submitted', 'reviewing', 'quoted', 'approved', 
    'in_progress', 'completed', 'cancelled'
  )),
  admin_notes TEXT,
  quoted_price DECIMAL(10,2),
  quoted_timeline_weeks INTEGER,
  
  -- Timestamps
  reviewed_at TIMESTAMP WITH TIME ZONE,
  quoted_at TIMESTAMP WITH TIME ZONE,
  approved_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_custom_orders_status ON public.custom_orders(status);
CREATE INDEX IF NOT EXISTS idx_custom_orders_customer_email ON public.custom_orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_custom_orders_created_at ON public.custom_orders(created_at);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_custom_orders_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_custom_orders_updated_at_trigger
  BEFORE UPDATE ON public.custom_orders
  FOR EACH ROW
  EXECUTE FUNCTION update_custom_orders_updated_at();

-- Enable RLS (Row Level Security)
ALTER TABLE public.custom_orders ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Allow authenticated users (admins) to read all custom orders
CREATE POLICY "Authenticated users can read custom orders" ON public.custom_orders
  FOR SELECT TO authenticated USING (true);

-- Allow authenticated users (admins) to update custom orders
CREATE POLICY "Authenticated users can update custom orders" ON public.custom_orders
  FOR UPDATE TO authenticated USING (true);

-- Allow anonymous users to insert new custom orders (public form submissions)
CREATE POLICY "Anyone can submit custom orders" ON public.custom_orders
  FOR INSERT TO anon WITH CHECK (true);

-- Allow authenticated users to insert custom orders (admin created)
CREATE POLICY "Authenticated users can create custom orders" ON public.custom_orders
  FOR INSERT TO authenticated WITH CHECK (true);

-- Grant necessary permissions
GRANT SELECT, INSERT, UPDATE ON public.custom_orders TO anon;
GRANT ALL ON public.custom_orders TO authenticated;
GRANT USAGE ON SEQUENCE custom_orders_id_seq TO anon;
GRANT USAGE ON SEQUENCE custom_orders_id_seq TO authenticated; 